AbhijeetMaske/SynergyWorks

- src/main/java/com/SynergyConnect/pageobject/AppSetup/BrandPage.java
**This pull request makes the following changes**
- Fix Issue #1 
**Checklist**
ping @AbhijeetMaske/SynergyWorks
> "Added locators -brandPage"

- src/main/java/com/SynergyConnect/pageobject/AppSetup/ApprovalConfigurationPage.java
**This pull request makes the following changes**
- Fix Issue #2 
**Checklist**
ping @AbhijeetMaske/SynergyWorks
> "Added locators-ApprovalConfigurationPage"

- Configuration/application.properties
- src/main/java/com/SynergyConnect/pageobject/AppSetup/ApprovalConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/BrandPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/UnitOfMeasurePage.java
- src/main/java/com/SynergyConnect/pageobject/HomePage.java
- src/main/java/com/SynergyConnect/pageobject/LoginPage.java
- src/main/java/com/SynergyConnect/utilities/ReadConfig.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/Brand.java
- src/test/java/com/SynergyConnect/testcases/Login.java
- suites/works.xml
This pull request makes the following changes
- Fix Issue #28 
**Tasks:**
**comment**
**Checklist**
Ping @AbhijeetMaske @Kavita1311
> "Create a Login Method"

- logs/SynergyWorks.log
- src/main/resources/log4j2.xml
This PR addresses issue:
- #35 
The implementation of logging with Log4j2 in the AppSetup module has been completed and successfully tested. The logs are now properly formatted and written to the specified file location. The following tasks have been accomplished:
**Tasks Completed:**
- Configured the log format as specified:
- %d{yyyy-MM-dd HH:mm:ss.SSS}: Timestamp with milliseconds.
- %-5p: Log level.
- %pid: Process ID.
- --- [%t]: Thread name.
- %c{1}: Logger name.
- : %m%n: Log message followed by a new line.
- Logs are now written to `log/SynergyWorks.log` in the user directory.
- Necessary directories are created if they do not exist.
- Added logging statements at appropriate locations.
- Ensured all critical operations and exception handling include log …
> Implemented Logging with Log4j2 in SynergyWorks

- Configuration/application.properties
- logs/SynergyWorks.log
- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/LoginPage.java
- src/main/java/com/SynergyConnect/utilities/AlertUtils.java
- src/main/java/com/SynergyConnect/utilities/ElementInteractionUtils.java
- src/test/java/com/SynergyConnect/testcases/Login.java
This PR introduces a new method to the TableUtils class to verify the presence of specified text in a table column. The method includes dynamic handling of the next button for pagination, enhancing flexibility and usability.
**Changes Made:**
**New Method Added: verifyTextInTable**
- Parameters:
- tableId: The ID of the table.
- tableColumnIndex: The column index to search in.
- searchText: The text to search for.
- nextButton: The WebElement represents the next button for pagination.
- Functionality:
- Iterates through table entries to find the specified text.
- Dynamically handles pagination by clicking the next button if available and enabled.
- Logs relevant information at each step for better traceability and debugging.
- Handles exceptions and logs error details …
> Email configuration

- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/LoginPage.java
- src/main/java/com/SynergyConnect/utilities/ElementInteractionUtils.java
- src/main/java/com/SynergyConnect/utilities/ExtentReportListener.java
- src/main/java/com/SynergyConnect/utilities/ReadConfig.java
- src/test/java/com/SynergyConnect/testcases/Login.java
- suites/works.xml
This Pull Request introduces methods to handle various operations related to the Email Configuration page in the AppSetup.EmailConfigurationPage.Java class. The implemented methods adhere to the project's naming conventions, coding standards, and include comprehensive exception handling.
- **1. Validation for Email Configuration Fields:**
- Implemented a method to validate the email configuration fields.
- Ensured the method checks for required field validations and proper format.
- Included exception handling to manage any errors during validation.
- **2. Add Email Configuration Data:**
- Implemented a method to add email configuration data.
- Ensured the data is correctly entered into the form and submitted.
- Included exception handling to manage …
> Implemented Email Configuration Operations in AppSetup.EmailConfigurationPage.JavaEmail configuration

- src/main/java/com/SynergyConnect/common/BaseClass.java
- src/test/java/com/SynergyConnect/testcases/Login.java
> "BaseClass [Fix]"

- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailGroupPage.java
This Pull Request introduces all necessary locators for the elements on the works/AppSetup/EmailGroup page. The locators have been added to the PageObject/appSetup/EmailGroupPage.java file, following the existing coding standards and naming conventions used in the project.
**Issue :**
- #8 
1. Review Elements: Reviewed the works/AppSetup/EmailGroup page to identify all interactive and static elements that require locators.
2. Define Locators: Defined locators for each identified element, including buttons, fields, and other interactive or static elements & Ensured locators are clearly commented for clarity and maintainability.
3. Test Locators: Tested the new locators to confirm they accurately identify the intended elements on the EmailGroup page. …
> Added Locators for Elements on works/AppSetup/EmailGroup Page

- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailTemplatePage.java
This Pull Request introduces all necessary locators for the elements on the works/AppSetup/EmailTemplatepage. The locators have been added to the PageObject/appSetup/EmailTemplatePage.java file, following the existing coding standards and naming conventions used in the project.
**Issue:**
- #9 
- Review Elements: Reviewed the works/AppSetup/EmailTemplate page to identify all interactive and static elements that require locators.
- Define Locators: Defined locators for each identified element, including buttons, fields, and other interactive or static elements & Ensured locators are commented on for clarity and maintainability.
- Test Locators: Tested the new locators to confirm they accurately identify the intended elements on the EmailTemplatepage. …
> "Email Template Locator [Added]"

- src/main/java/com/SynergyConnect/common/BaseClass.java
- src/test/java/com/SynergyConnect/testcases/Login.java
AppSetup | Email template [Added]
> AppSetup | Email template [Added]

- src/test/java/com/SynergyConnect/testcases/AppSetup/ApprovalConfiguration.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/BankName.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/BillingCycle.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/CompanyType.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/CostCodeFieldConfiguration.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/Depreciation.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/EmailConfiguration.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/EmailGroup.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/EmailTemplate.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/EmployerBankMaster.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/ExpenseType.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/Item.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/ItemCategory.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/NatureOfPayment.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/OfacConfiguration.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/ParticipantType.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/TatConfiguration.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/TeamConfiguration.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/TelecommunicationServiceProvider.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/TransportationMode.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/UidConfiguration.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/UnitOfMeasure.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/VoucherMonthlyLimit.java
> "Test/appSetup [Added]"

- src/main/java/com/SynergyConnect/common/BaseClass.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailConfigurationPage.java
- src/main/java/com/SynergyConnect/utilities/ElementInteractionUtils.java
This Pull Request addresses a bug in the `verifyTextInTableAndPerformAction` method in src/main/java/com/SynergyConnect/utilities/ElementInteractionUtils.java. The method was incorrectly performing actions on the first row instead of the specified index row (I).
**Issue**
- #49 
**Bug Details:**
- Issue: The method `verifyTextInTableAndPerformAction` was not performing the action on the correct row index (I). Instead, the action was always being performed on the first row.
- Impact: This bug caused incorrect data manipulation and potential test failures, as actions were not being performed on the intended table rows.
**Fix Implemented:**
- Update Method Logic: Adjusted the logic within `verifyTextInTableAndPerformAction` to correctly target and perform actions on the …
> Fix:  verifyTextInTableAndPerformAction Method to Perform Action on Correct Row

- src/main/java/com/SynergyConnect/pageobject/AppSetup/UnitOfMeasurePage.java
This Pull Request introduces all necessary locators for the elements on the works/AppSetup/UnitOfMeasurement page. The locators have been added to the PageObject/appSetup/UnitOfMeasurementPage.java file, following the existing coding standards and naming conventions used in the project.
**Issue:**
- #27 
1. Review Elements: 
- Reviewed the works/AppSetup/UnitOfMeasurement page to identify all interactive and static elements that require locators.
2. Define Locators: 
- Ensured locators are commented for clarity and maintainability.
3. Test Locators: 
- Tested the new locators to confirm they accurately identify the intended elements …
> Added Locators for Elements on works/AppSetup/UnitOfMeasurement Page

- Configuration/application.properties
- logs/SynergyWorks.log
- src/main/java/com/SynergyConnect/common/BaseClass.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/UnitOfMeasurePage.java
- src/main/java/com/SynergyConnect/utilities/ElementInteractionUtils.java
App setup -> Unit of measurement [Added]
> App setup -> Unit of measurement [Added]

- src/main/java/com/SynergyConnect/pageobject/AppSetup/CompanyTypePage.java
> Company Type [Added]

- src/main/java/com/SynergyConnect/pageobject/AppSetup/BankNamePage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/CompanyTypePage.java
- src/main/java/com/SynergyConnect/pageobject/LoginPage.java
- src/main/java/com/SynergyConnect/utilities/ExtentReportListener.java
This Pull Request introduces all necessary locators for the elements on the works/AppSetup/BankName page. The locators have been added to the PageObject/appSetup/BankNamePage.java file, following the existing coding standards and naming conventions used in the project.
**Issue:**
- #6 
1. Review Elements: 
- Reviewed the works/AppSetup/BankName page to identify all interactive and static elements that require locators.
2. Define Locators: 
- Ensured locators are commented for clarity and maintainability.
3. Test Locators: 
- Tested the new locators to confirm they accurately identify the intended elements on the BankName page. …
> Added Locators for Elements on works/AppSetup/BankName Page

- src/main/java/com/SynergyConnect/pageobject/AppSetup/BankNamePage.java
- src/main/java/com/SynergyConnect/pageobject/LoginPage.java
- src/main/java/com/SynergyConnect/utilities/ExtentReportListener.java
This PR merges the feature branch into the AppSetupbranch. It includes the following updates:
- Added Locators for Elements on works/AppSetup/BankName Page
**Issue**
- #54 
- #6
> Merge Feature Branch into AppSetup

- src/main/java/com/SynergyConnect/pageobject/AppSetup/OfacConfigurationPage.java
This Pull Request introduces all necessary locators for the elements on the `works/AppSetup/OfacConfiguration` page. The locators have been added to the `PageObject/appSetup/OfacConfigurationPage.java` file, following the existing coding standards and naming conventions used in the project.
- Reviewed the works/AppSetup/OfacConfiguration page to identify all interactive and static elements that require locators.
- Ensured locators are clearly commented for clarity and maintainability.
- Tested the new locators to confirm they accurately identify the intended elements on the …
> Add Locators for Elements on works/AppSetup/OfacConfiguration Page

- src/main/java/com/SynergyConnect/utilities/AlertUtils.java
- src/main/java/com/SynergyConnect/utilities/ApiUtils.java
- src/main/java/com/SynergyConnect/utilities/CustomAssertions.java
- src/main/java/com/SynergyConnect/utilities/DataProviderUtils.java
- src/main/java/com/SynergyConnect/utilities/DatabaseUtils.java
- src/main/java/com/SynergyConnect/utilities/DateTimeUtils.java
- src/main/java/com/SynergyConnect/utilities/EmailUtils.java
- src/main/java/com/SynergyConnect/utilities/ExcelUtils.java
- src/main/java/com/SynergyConnect/utilities/ExtentReportListener.java
- src/main/java/com/SynergyConnect/utilities/FileUtils.java
- src/main/java/com/SynergyConnect/utilities/ReadConfig.java
- src/main/java/com/SynergyConnect/utilities/RetryAnalyzer.java
- src/main/java/com/SynergyConnect/utilities/ScreenshotUtils.java
- src/main/java/com/SynergyConnect/utilities/UtilMethods.java
> Log message [updated]

- logs/SynergyWorks.log
- src/main/java/com/SynergyConnect/common/BaseClass.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/CompanyTypePage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/OfacConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/LoginPage.java
- src/main/java/com/SynergyConnect/utilities/ReadConfig.java
This Pull Request introduces all necessary locators for the elements on the `works/AppSetup/companyType` page. The locators have been added to the `PageObject/appSetup/companyType.java` file, following the existing coding standards and naming conventions used in the project.
- Reviewed the works/AppSetup/companyType page to identify all interactive and static elements that require locators.
- Ensured locators are clearly commented for clarity and maintainability.
- Tested the new locators to confirm they accurately identify the intended elements on the `companyType` page. …
> Add Locators for Elements on works/AppSetup/companyType Page

- logs/SynergyWorks.log
- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/ItemCategoryPage.java
This Pull Request introduces all necessary locators for the elements on the `works/AppSetup/ItemCategory` page. The locators have been added to the `PageObject/appSetup/ItemCategory.java` file, following the existing coding standards and naming conventions used in the project.
- Reviewed the `works/AppSetup/ItemCategory` page to identify all interactive and static elements that require locators.
- Tested the new locators to confirm they accurately identify the intended elements on the `ItemCategory` page. …
> Added Locators for Elements on works/AppSetup/ItemCategory Page

- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/ItemCategoryPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/ItemPage.java
- src/test/java/com/SynergyConnect/testcases/AppSetup/EmailConfiguration.java
This Pull Request introduces all necessary locators for the elements on the `works/AppSetup/Item` page. The locators have been added to the `PageObject/appSetup/Item.java` file, following the existing coding standards and naming conventions used in the project.
- Reviewed the `works/AppSetup/Item` page to identify all interactive and static elements that require locators.
- Tested the new locators to confirm they accurately identify the intended elements on the `Item` page.
**Requirements:**
- Followed the …
> Added Locators for Elements on works/AppSetup/Item Page

- src/main/java/com/SynergyConnect/pageobject/AppSetup/CompanyTypePage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/TatConfigurationPage.java
This Pull Request introduces all necessary locators for the elements on the `works/AppSetup/TatConfiguration` page. The locators have been added to the `PageObject/appSetup/TatConfiguration.java` file, following the existing coding standards and naming conventions used in the project.
- Reviewed the `works/AppSetup/TatConfiguration` page to identify all interactive and static elements that require locators.
- Tested the new locators to confirm they accurately identify the intended elements on the …
> Added Locators for Elements on works/AppSetup/TatConfiguration Page

- src/main/java/com/SynergyConnect/pageobject/AppSetup/ApprovalConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/BankNamePage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/BrandPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailGroupPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/EmailTemplatePage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/ItemPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/OfacConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/TatConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/TeamConfigurationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/UnitOfMeasurePage.java
This Pull Request introduces all necessary locators for the elements on the `works/AppSetup/TeamConfiguration` page. The locators have been added to the `PageObject/appSetup/TeamConfiguration.java` file, following the existing coding standards and naming conventions used in the project.
- Reviewed the `works/AppSetup/TeamConfiguration` page to identify all interactive and static elements that require locators.
- Tested the new locators to confirm they accurately identify the intended elements on the …
> Added Locators for Elements on works/AppSetup/TeamConfiguration Page

- src/main/java/com/SynergyConnect/pageobject/AppSetup/DepreciationPage.java
- src/main/java/com/SynergyConnect/pageobject/AppSetup/ItemPage.java
This Pull Request introduces all necessary locators for the elements on the `works/AppSetup/Depreciation` page. The locators have been added to the `PageObject/appSetup/Depreciation.java` file, following the existing coding standards and naming conventions used in the project.
- Reviewed the `works/AppSetup/Depreciation` page to identify all interactive and static elements that require locators.
- Tested the new locators to confirm they accurately identify the intended elements on the `Depreciation` page. …
> Added Locators for Elements on works/AppSetup/Depreciation Page

- src/main/java/com/SynergyConnect/pageobject/AppSetup/VoucherMonthlyLimitPage.java
This Pull Request introduces all necessary locators for the elements on the `works/AppSetup/VoucherMonthlyLimit` page. The locators have been added to the `PageObject/appSetup/VoucherMonthlyLimit.java` file, following the existing coding standards and naming conventions used in the project.
- Reviewed the `works/AppSetup/VoucherMonthlyLimit` page to identify all interactive and static elements that require locators.
- Tested the new locators to confirm they accurately identify the intended elements on the …
> Added Locators for Elements on works/AppSetup/VoucherMonthlyLimit Page
